# Generated by Django 3.2.10 on 2022-06-13 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images')),
                ('contacts', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images')),
                ('description', models.TextField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=200)),
                ('rate_by_design', models.PositiveSmallIntegerField(choices=[(1, '1 - Could do better'), (2, '2 - Keep trying'), (3, '3 - Almost there,'), (4, '4 - Nice'), (5, '5 - I like the effort put in this'), (6, '6 - Good'), (7, '7 - Very Goood'), (8, '8 -  woooooow!'), (9, '9 - Perfect'), (10, '10 - Amazing')])),
                ('rate_by_usability', models.PositiveSmallIntegerField(choices=[(1, '1 - Could do better'), (2, '2 - Keep trying'), (3, '3 - Almost there,'), (4, '4 - Nice'), (5, '5 - I like the effort put in this'), (6, '6 - Good'), (7, '7 - Very Goood'), (8, '8 -  woooooow!'), (9, '9 - Perfect'), (10, '10 - Amazing')])),
                ('rate_by_content', models.PositiveSmallIntegerField(choices=[(1, '1 - Could do better'), (2, '2 - Keep trying'), (3, '3 - Almost there,'), (4, '4 - Nice'), (5, '5 - I like the effort put in this'), (6, '6 - Good'), (7, '7 - Very Goood'), (8, '8 -  woooooow!'), (9, '9 - Perfect'), (10, '10 - Amazing')])),
                ('like', models.PositiveIntegerField(default=0)),
                ('unlike', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
