# Generated by Django 3.2.10 on 2022-06-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
